### ISSUE TITLE
Configuration file for elixir dependencies

### ISSUE THREAD

**Issue by SunnyRichards** [Supersonido/rebar3_elixir#2]
Hello, I am using elixir's (ex_aws) in my Erlang app through your library. For the proper functioning of **ex_aws**, I need to provide the config.exs

What is the proper way to do this? Can I somehow use my _sys.config_ to provide those configs ?

> config :ex_aws,
  debug_requests: true,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  region: "us-east-1"

**Comment by ghost** [comment]
@SunnyRichards   could do something like.. 

```
application:set_all_env(ex_aws, [{ 
debug_requests, true },
 {access_key_id, <<“your AWS access key is”>>, …. 
```

**Comment by SunnyRichards** [comment]
@bryanhuntesl Thank You
